# Generated by Django 5.2.7 on 2026-08-30 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, verbose_name='репозиторий GitHub')),
                ('live_url', models.URLField(blank=True, verbose_name='живая демонстрация')),
                ('video_url', models.URLField(blank=True, verbose_name='демо-видео')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='описание')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('submitted', 'отправлено'), ('reviewed', 'проверено')], default='draft', max_length=16, verbose_name='статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='оценка')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='заметки проверяющего')),
                ('is_winner', models.BooleanField(default=False, verbose_name='победитель')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contest', verbose_name='контест')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['contest', 'status'], name='submissions_contest_860f39_idx')],
                'constraints': [models.UniqueConstraint(fields=('contest', 'user'), name='unique_submission_per_contest_and_user')],
            },
        ),
    ]
