/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/contests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список и создание контестов в админке. */
        get: operations["admin_contests_list"];
        put?: never;
        /** @description Список и создание контестов в админке. */
        post: operations["admin_contests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/contests/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Просмотр, правка и удаление контеста. */
        get: operations["admin_contests_retrieve"];
        /** @description Просмотр, правка и удаление контеста. */
        put: operations["admin_contests_update"];
        post?: never;
        /** @description Просмотр, правка и удаление контеста. */
        delete: operations["admin_contests_destroy"];
        options?: never;
        head?: never;
        /** @description Просмотр, правка и удаление контеста. */
        patch: operations["admin_contests_partial_update"];
        trace?: never;
    };
    "/api/admin/contests/{id}/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Опубликовать контест
         * @description Публикация черновика.
         */
        post: operations["admin_contests_publish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Очередь проверки взносов. */
        get: operations["admin_payments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/payments/{id}/decision/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Решение по взносу
         * @description Принять или отклонить взнос.
         */
        post: operations["admin_payments_decision_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Счётчики админ-панели
         * @description Счётчики для админ-панели.
         */
        get: operations["admin_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Заявки
         * @description Список заявок в админке.
         */
        get: operations["admin_submissions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/submissions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Заявка
         * @description Экран проверки заявки.
         */
        get: operations["admin_submissions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Сохранить проверку
         * @description Экран проверки заявки.
         */
        patch: operations["admin_submissions_partial_update"];
        trace?: never;
    };
    "/api/admin/submissions/{id}/screen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Проверить репозиторий заново
         * @description Перезапуск автоматической проверки по кнопке.
         */
        post: operations["admin_submissions_screen_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Пользователи
         * @description Список пользователей.
         */
        get: operations["admin_users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выйти
         * @description Выход: чистим куки и гасим refresh-токен.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь
         * @description Текущий пользователь по куке.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновить сессию
         * @description Обновление access-токена по refresh-куке.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram/exchange/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обменять код на сессию
         * @description Шаг 3: обменять подтверждённый код на сессию в куках.
         */
        post: operations["auth_telegram_exchange_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Начать вход через Telegram
         * @description Шаг 1: выдать одноразовый код и ссылку на бота.
         */
        post: operations["auth_telegram_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Статус попытки входа
         * @description Шаг 2: фронтенд опрашивает этот эндпоинт, пока ждёт подтверждения.
         */
        get: operations["auth_telegram_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список контестов
         * @description Публичный список опубликованных контестов.
         */
        get: operations["contests_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Контест
         * @description Страница контеста.
         */
        get: operations["contests_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{slug}/participation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Участие в контесте
         * @description Состояние участия: сумма, реквизиты и свой чек.
         */
        get: operations["contests_participation_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{slug}/participation/receipt/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузить чек
         * @description Чек, загруженный прямо на сайте.
         */
        post: operations["contests_participation_receipt_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{slug}/participation/via-bot/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отправить чек через бота
         * @description Участник обещает прислать чек в бот.
         */
        post: operations["contests_participation_via_bot_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{slug}/submission/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Моя заявка
         * @description Своя заявка на контест: одна на человека, правится до дедлайна.
         */
        get: operations["contests_submission_retrieve"];
        /**
         * Сохранить черновик заявки
         * @description Своя заявка на контест: одна на человека, правится до дедлайна.
         */
        put: operations["contests_submission_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{slug}/submission/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отправить решение
         * @description Перевод заявки из черновика в отправленные.
         */
        post: operations["contests_submission_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/featured/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Контест на главной
         * @description Контест для главной страницы.
         *
         *     Всегда отдаёт объект с ключом ``contest``, который равен ``null``, если
         *     активного контеста нет: это состояние «Сейчас нет активного контеста».
         *     Обёртка, а не голый ``null``, по двум причинам — DRF рендерит None пустым
         *     телом без Content-Type, и в этот же ответ потом добавятся общие счётчики
         *     главной, не ломая формат.
         */
        get: operations["contests_featured_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверка состояния сервиса
         * @description Проверка живости: приложение отвечает и база доступна.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/notify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подписаться на анонсы
         * @description Кнопка «Уведомить меня», когда активного контеста нет.
         */
        post: operations["me_notify_create"];
        /**
         * Отписаться от анонсов
         * @description Кнопка «Уведомить меня», когда активного контеста нет.
         */
        delete: operations["me_notify_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История заявок для своего профиля. */
        get: operations["me_submissions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Профиль участника
         * @description Публичный профиль участника.
         *
         *     Живёт в этом приложении, а не в users: почти всё содержимое — история
         *     заявок, и так users не приходится зависеть от submissions.
         */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Создание и редактирование контеста админом. */
        AdminContest: {
            readonly id: number;
            /** Номер */
            readonly number: number;
            readonly display_number: string;
            /** Адрес */
            slug?: string;
            /** Название */
            title: string;
            /** Описание */
            description?: string;
            requirements?: string[];
            /**
             * Призовой фонд
             * Format: decimal
             */
            prize_pool?: string;
            /** Валюта */
            currency?: components["schemas"]["CurrencyEnum"];
            /**
             * Взнос за участие
             * Format: decimal
             * @description Ноль — участие бесплатное.
             */
            entry_fee?: string;
            /**
             * @description Платный ли контест.
             *
             *     Признак вычисляется из суммы, а не хранится отдельным флагом: иначе
             *     возможно противоречивое состояние «платный, но взнос равен нулю».
             */
            readonly is_paid: boolean;
            /**
             * Начало
             * Format: date-time
             */
            starts_at?: string | null;
            /**
             * Дедлайн
             * Format: date-time
             */
            deadline: string;
            /** Статус */
            status?: components["schemas"]["ContestStatusEnum"];
            readonly state: components["schemas"]["ContestStateEnum"];
            /** Показывать на главной */
            is_featured?: boolean;
            /**
             * Создан
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлён
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** @description Создание и редактирование контеста админом. */
        AdminContestRequest: {
            /** Адрес */
            slug?: string;
            /** Название */
            title: string;
            /** Описание */
            description?: string;
            requirements?: string[];
            /**
             * Призовой фонд
             * Format: decimal
             */
            prize_pool?: string;
            /** Валюта */
            currency?: components["schemas"]["CurrencyEnum"];
            /**
             * Взнос за участие
             * Format: decimal
             * @description Ноль — участие бесплатное.
             */
            entry_fee?: string;
            /**
             * Начало
             * Format: date-time
             */
            starts_at?: string | null;
            /**
             * Дедлайн
             * Format: date-time
             */
            deadline: string;
            /** Статус */
            status?: components["schemas"]["ContestStatusEnum"];
            /** Показывать на главной */
            is_featured?: boolean;
        };
        AdminPayment: {
            readonly id: number;
            readonly username: string;
            readonly telegram_username: string;
            readonly contest_title: string;
            readonly contest_slug: string;
            /**
             * Сумма
             * Format: decimal
             */
            readonly amount: string;
            /** Валюта */
            readonly currency: string;
            /** Статус */
            readonly status: components["schemas"]["PaymentStatusEnum"];
            readonly receipt_url: string | null;
            /** @description file — можно открыть, telegram — только в чате, none — чека нет. */
            readonly receipt_source: string;
            /** Причина отказа */
            readonly rejection_reason: string;
            /**
             * Чек получен
             * Format: date-time
             */
            readonly submitted_at: string | null;
            /**
             * Проверен
             * Format: date-time
             */
            readonly reviewed_at: string | null;
            /**
             * Создан
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** @description Четыре плитки на админ-панели. */
        AdminStats: {
            total_users: number;
            active_contests: number;
            submissions: number;
            pending_review: number;
        };
        /** @description Экран проверки: здесь оценка и внутренние заметки уже видны. */
        AdminSubmissionDetail: {
            readonly id: number;
            readonly username: string;
            readonly telegram_username: string;
            readonly contest_title: string;
            readonly contest_slug: string;
            /**
             * Репозиторий GitHub
             * Format: uri
             */
            readonly github_url: string;
            /**
             * Живая демонстрация
             * Format: uri
             */
            readonly live_url: string;
            /**
             * Демо-видео
             * Format: uri
             */
            readonly video_url: string;
            /** Описание */
            readonly description: string;
            readonly repo_name: string;
            /** Статус */
            readonly status: components["schemas"]["SubmissionStatusEnum"];
            readonly display_status: components["schemas"]["DisplayStatusEnum"];
            /** Оценка */
            score?: number | null;
            /** Заметки проверяющего */
            reviewer_notes?: string;
            /** Победитель */
            is_winner?: boolean;
            /**
             * Проверено
             * Format: date-time
             */
            readonly reviewed_at: string | null;
            /**
             * Отправлено
             * Format: date-time
             */
            readonly submitted_at: string | null;
            /**
             * Создана
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** @description Заявка, навигация по очереди и итог автоматической проверки. */
        AdminSubmissionEnvelope: {
            submission: components["schemas"]["AdminSubmissionDetail"];
            navigation: components["schemas"]["Navigation"];
            screening: components["schemas"]["Screening"] | null;
        };
        /** @description Строка в списке заявок админки. */
        AdminSubmissionList: {
            readonly id: number;
            readonly username: string;
            readonly contest_title: string;
            readonly contest_slug: string;
            readonly repo_name: string;
            /** Статус */
            readonly status: components["schemas"]["SubmissionStatusEnum"];
            readonly display_status: components["schemas"]["DisplayStatusEnum"];
            /** Оценка */
            readonly score: number | null;
            /** Победитель */
            readonly is_winner: boolean;
            /**
             * Отправлено
             * Format: date-time
             */
            readonly submitted_at: string | null;
        };
        AdminUser: {
            readonly id: number;
            /**
             * Имя пользователя
             * @description Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
             */
            readonly username: string;
            readonly telegram_id: number;
            /** Username в Telegram */
            readonly telegram_username: string;
            /** Имя */
            readonly first_name: string;
            /** Фамилия */
            readonly last_name: string;
            /**
             * Статус персонала
             * @description Отметьте, если пользователь может входить в административную часть сайта.
             */
            readonly is_staff: boolean;
            /**
             * Активный
             * @description Отметьте, если пользователь должен считаться активным. Уберите эту отметку вместо удаления учётной записи.
             */
            readonly is_active: boolean;
            readonly submissions_count: number;
            readonly wins_count: number;
            /**
             * Создан
             * Format: date-time
             */
            readonly created_at: string;
        };
        AuthExchangeRequestRequest: {
            nonce: string;
            client_secret: string;
        };
        AuthStartResponse: {
            nonce: string;
            client_secret: string;
            /** Format: uri */
            deep_link: string;
            /** Format: date-time */
            expires_at: string;
            expires_in: number;
        };
        AuthStatusResponse: {
            status: string;
        };
        /** @description Карточка контеста в списке и на главной. */
        ContestDetail: {
            readonly id: number;
            /** Номер */
            readonly number: number;
            readonly display_number: string;
            /** Адрес */
            readonly slug: string;
            /** Название */
            readonly title: string;
            /** Описание */
            readonly description: string;
            /**
             * Призовой фонд
             * Format: decimal
             */
            readonly prize_pool: string;
            /** Валюта */
            readonly currency: components["schemas"]["CurrencyEnum"];
            /**
             * Дедлайн
             * Format: date-time
             */
            readonly deadline: string;
            /**
             * @description Сколько секунд осталось до дедлайна.
             *
             *     Отдаём числом, а не строкой: обратный отсчёт на фронтенде тикает сам,
             *     и ему не нужно доверять часам на устройстве пользователя.
             */
            readonly seconds_left: number;
            /**
             * @description Число участников: черновики не считаются участием.
             *
             *     Значение берётся из аннотации, если вьюха её сделала, иначе
             *     считается запросом — чтобы сериализатор работал и вне списка.
             */
            readonly participants_count: number;
            /**
             * Взнос за участие
             * Format: decimal
             * @description Ноль — участие бесплатное.
             */
            readonly entry_fee: string;
            /**
             * @description Платный ли контест.
             *
             *     Признак вычисляется из суммы, а не хранится отдельным флагом: иначе
             *     возможно противоречивое состояние «платный, но взнос равен нулю».
             */
            readonly is_paid: boolean;
            readonly state: components["schemas"]["ContestStateEnum"];
            readonly requirements: string[];
            /**
             * Начало
             * Format: date-time
             */
            readonly starts_at: string | null;
            /** @description Можно ли сейчас присылать и править решения. */
            readonly accepts_submissions: boolean;
            readonly my_submission: components["schemas"]["MySubmission"] | null;
            /**
             * Создан
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** @description Карточка контеста в списке и на главной. */
        ContestList: {
            readonly id: number;
            /** Номер */
            readonly number: number;
            readonly display_number: string;
            /** Адрес */
            readonly slug: string;
            /** Название */
            readonly title: string;
            /** Описание */
            readonly description: string;
            /**
             * Призовой фонд
             * Format: decimal
             */
            readonly prize_pool: string;
            /** Валюта */
            readonly currency: components["schemas"]["CurrencyEnum"];
            /**
             * Дедлайн
             * Format: date-time
             */
            readonly deadline: string;
            /**
             * @description Сколько секунд осталось до дедлайна.
             *
             *     Отдаём числом, а не строкой: обратный отсчёт на фронтенде тикает сам,
             *     и ему не нужно доверять часам на устройстве пользователя.
             */
            readonly seconds_left: number;
            /**
             * @description Число участников: черновики не считаются участием.
             *
             *     Значение берётся из аннотации, если вьюха её сделала, иначе
             *     считается запросом — чтобы сериализатор работал и вне списка.
             */
            readonly participants_count: number;
            /**
             * Взнос за участие
             * Format: decimal
             * @description Ноль — участие бесплатное.
             */
            readonly entry_fee: string;
            /**
             * @description Платный ли контест.
             *
             *     Признак вычисляется из суммы, а не хранится отдельным флагом: иначе
             *     возможно противоречивое состояние «платный, но взнос равен нулю».
             */
            readonly is_paid: boolean;
            readonly state: components["schemas"]["ContestStateEnum"];
        };
        /**
         * @description * `draft` - черновик
         *     * `live` - идёт
         *     * `ended` - завершён
         *     * `archived` - в архиве
         * @enum {string}
         */
        ContestStateEnum: "draft" | "live" | "ended" | "archived";
        /**
         * @description * `draft` - черновик
         *     * `published` - опубликован
         *     * `archived` - в архиве
         * @enum {string}
         */
        ContestStatusEnum: "draft" | "published" | "archived";
        /**
         * @description * `USD` - доллар США
         *     * `TJS` - сомони
         *     * `RUB` - рубль
         * @enum {string}
         */
        CurrencyEnum: "USD" | "TJS" | "RUB";
        /**
         * @description * `accept` - accept
         *     * `reject` - reject
         * @enum {string}
         */
        DecisionEnum: "accept" | "reject";
        /**
         * @description * `draft` - черновик
         *     * `submitted` - отправлено
         *     * `reviewed` - проверено
         *     * `winner` - победитель
         * @enum {string}
         */
        DisplayStatusEnum: "draft" | "submitted" | "reviewed" | "winner";
        /** @description Ответ главной страницы; contest равен null, когда ничего не идёт. */
        FeaturedContest: {
            contest: components["schemas"]["ContestDetail"] | null;
        };
        /** @description Своё участие глазами участника. */
        MyPayment: {
            readonly id: number;
            /**
             * Сумма
             * Format: decimal
             */
            readonly amount: string;
            /** Валюта */
            readonly currency: string;
            /** Статус */
            readonly status: components["schemas"]["PaymentStatusEnum"];
            readonly has_receipt: boolean;
            /** Ждём чек в боте */
            readonly expects_receipt_in_bot: boolean;
            /** Причина отказа */
            readonly rejection_reason: string;
            /**
             * Чек получен
             * Format: date-time
             */
            readonly submitted_at: string | null;
            /**
             * Создан
             * Format: date-time
             */
            readonly created_at: string;
        };
        /**
         * @description Своя заявка глазами участника.
         *
         *     Ни ``score``, ни ``reviewer_notes`` тут нет и быть не должно: на макете
         *     проверки заметки прямо помечены как невидимые для участника.
         */
        MySubmission: {
            readonly id: number;
            readonly contest_title: string;
            readonly contest_slug: string;
            /**
             * Репозиторий GitHub
             * Format: uri
             */
            github_url?: string;
            /**
             * Живая демонстрация
             * Format: uri
             */
            live_url?: string;
            /**
             * Демо-видео
             * Format: uri
             */
            video_url?: string;
            /** Описание */
            description?: string;
            /** Статус */
            readonly status: components["schemas"]["SubmissionStatusEnum"];
            readonly display_status: components["schemas"]["DisplayStatusEnum"];
            readonly is_editable: boolean;
            /**
             * Отправлено
             * Format: date-time
             */
            readonly submitted_at: string | null;
            /**
             * Создана
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлена
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** @description submission равен null, если участник ещё ничего не отправлял. */
        MySubmissionEnvelope: {
            submission: components["schemas"]["MySubmission"] | null;
        };
        /**
         * @description Своя заявка глазами участника.
         *
         *     Ни ``score``, ни ``reviewer_notes`` тут нет и быть не должно: на макете
         *     проверки заметки прямо помечены как невидимые для участника.
         */
        MySubmissionRequest: {
            /**
             * Репозиторий GitHub
             * Format: uri
             */
            github_url?: string;
            /**
             * Живая демонстрация
             * Format: uri
             */
            live_url?: string;
            /**
             * Демо-видео
             * Format: uri
             */
            video_url?: string;
            /** Описание */
            description?: string;
        };
        /** @description Счётчик «3 / 36» и стрелки на экране проверки. */
        Navigation: {
            position: number | null;
            total: number;
            previous_id: number | null;
            next_id: number | null;
        };
        PaginatedAdminContestList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminContest"][];
        };
        PaginatedAdminPaymentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminPayment"][];
        };
        PaginatedAdminSubmissionListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminSubmissionList"][];
        };
        PaginatedAdminUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminUser"][];
        };
        PaginatedContestListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ContestList"][];
        };
        PaginatedProfileSubmissionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProfileSubmission"][];
        };
        /** @description Что нужно знать странице контеста об участии. */
        Participation: {
            is_paid: boolean;
            /** Format: decimal */
            entry_fee: string;
            currency: string;
            requisites: string;
            can_submit: boolean;
            payment: components["schemas"]["MyPayment"] | null;
        };
        /** @description Создание и редактирование контеста админом. */
        PatchedAdminContestRequest: {
            /** Адрес */
            slug?: string;
            /** Название */
            title?: string;
            /** Описание */
            description?: string;
            requirements?: string[];
            /**
             * Призовой фонд
             * Format: decimal
             */
            prize_pool?: string;
            /** Валюта */
            currency?: components["schemas"]["CurrencyEnum"];
            /**
             * Взнос за участие
             * Format: decimal
             * @description Ноль — участие бесплатное.
             */
            entry_fee?: string;
            /**
             * Начало
             * Format: date-time
             */
            starts_at?: string | null;
            /**
             * Дедлайн
             * Format: date-time
             */
            deadline?: string;
            /** Статус */
            status?: components["schemas"]["ContestStatusEnum"];
            /** Показывать на главной */
            is_featured?: boolean;
        };
        /** @description Экран проверки: здесь оценка и внутренние заметки уже видны. */
        PatchedAdminSubmissionDetailRequest: {
            /** Оценка */
            score?: number | null;
            /** Заметки проверяющего */
            reviewer_notes?: string;
            /** Победитель */
            is_winner?: boolean;
        };
        /** @description Решение админа по чеку. */
        PaymentDecisionRequest: {
            decision: components["schemas"]["DecisionEnum"];
            reason?: string;
        };
        /**
         * @description * `awaiting_receipt` - ждём чек
         *     * `pending` - на проверке
         *     * `accepted` - принят
         *     * `rejected` - отклонён
         * @enum {string}
         */
        PaymentStatusEnum: "awaiting_receipt" | "pending" | "accepted" | "rejected";
        /** @description Строка истории на странице профиля. */
        ProfileSubmission: {
            readonly id: number;
            readonly contest_title: string;
            readonly contest_slug: string;
            readonly repo_name: string;
            readonly display_status: components["schemas"]["DisplayStatusEnum"];
            /**
             * Отправлено
             * Format: date-time
             */
            readonly submitted_at: string | null;
            /**
             * Создана
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** @description Страница профиля участника. */
        PublicProfile: {
            user: components["schemas"]["User"];
            submissions_count: number;
            wins_count: number;
            submissions: components["schemas"]["ProfileSubmission"][];
        };
        /** @description Чек, загруженный с сайта. */
        ReceiptUploadRequest: {
            /** Format: binary */
            receipt: string;
        };
        /** @description Итог автоматической проверки для экрана разбора заявки. */
        Screening: {
            /** Статус */
            readonly status: components["schemas"]["ScreeningStatusEnum"];
            /** Находки */
            readonly findings: unknown;
            /** О репозитории */
            readonly repo_meta: unknown;
            /** Ответ демо */
            readonly live_status: number | null;
            /** Файлов проверено */
            readonly files_scanned: number;
            readonly high_severity_count: number;
            readonly has_findings: boolean;
            /** Ошибка */
            readonly error: string;
            /**
             * Проверено
             * Format: date-time
             */
            readonly checked_at: string | null;
        };
        /**
         * @description * `pending` - в очереди
         *     * `done` - проверено
         *     * `failed` - не удалось
         * @enum {string}
         */
        ScreeningStatusEnum: "pending" | "done" | "failed";
        /**
         * @description * `draft` - черновик
         *     * `submitted` - отправлено
         *     * `reviewed` - проверено
         * @enum {string}
         */
        SubmissionStatusEnum: "draft" | "submitted" | "reviewed";
        /** @description Профиль текущего пользователя. */
        User: {
            readonly id: number;
            /**
             * Имя пользователя
             * @description Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
             */
            readonly username: string;
            readonly display_name: string;
            /** Username в Telegram */
            readonly telegram_username: string;
            /** Имя */
            readonly first_name: string;
            /** Фамилия */
            readonly last_name: string;
            /**
             * Аватар
             * Format: uri
             */
            readonly photo_url: string;
            readonly is_admin: boolean;
            /** Уведомлять о новых контестах */
            readonly notify_opt_in: boolean;
            /**
             * Создан
             * Format: date-time
             */
            readonly created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_contests_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminContestList"];
                };
            };
        };
    };
    admin_contests_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminContestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminContestRequest"];
                "multipart/form-data": components["schemas"]["AdminContestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContest"];
                };
            };
        };
    };
    admin_contests_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContest"];
                };
            };
        };
    };
    admin_contests_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminContestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminContestRequest"];
                "multipart/form-data": components["schemas"]["AdminContestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContest"];
                };
            };
        };
    };
    admin_contests_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_contests_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminContestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminContestRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminContestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContest"];
                };
            };
        };
    };
    admin_contests_publish_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContest"];
                };
            };
        };
    };
    admin_payments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminPaymentList"];
                };
            };
        };
    };
    admin_payments_decision_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentDecisionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaymentDecisionRequest"];
                "multipart/form-data": components["schemas"]["PaymentDecisionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPayment"];
                };
            };
        };
    };
    admin_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
        };
    };
    admin_submissions_list: {
        parameters: {
            query?: {
                /** @description Слаг контеста */
                contest?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Поиск по участнику или репозиторию */
                search?: string;
                /** @description Фильтр статуса; winner — только победители */
                status?: "draft" | "reviewed" | "submitted" | "winner";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminSubmissionListList"];
                };
            };
        };
    };
    admin_submissions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionEnvelope"];
                };
            };
        };
    };
    admin_submissions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminSubmissionDetailRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminSubmissionDetailRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminSubmissionDetailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionEnvelope"];
                };
            };
        };
    };
    admin_submissions_screen_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_users_list: {
        parameters: {
            query?: {
                /** @description Только администраторы */
                is_staff?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Поиск по логину, имени или Telegram ID */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminUserList"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_telegram_exchange_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthExchangeRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AuthExchangeRequestRequest"];
                "multipart/form-data": components["schemas"]["AuthExchangeRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_telegram_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStartResponse"];
                };
            };
        };
    };
    auth_telegram_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
        };
    };
    contests_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Фильтр: live или ended. По умолчанию — все опубликованные. */
                state?: "ended" | "live";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContestListList"];
                };
            };
        };
    };
    contests_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestDetail"];
                };
            };
        };
    };
    contests_participation_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
        };
    };
    contests_participation_receipt_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ReceiptUploadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReceiptUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
        };
    };
    contests_participation_via_bot_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
        };
    };
    contests_submission_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubmissionEnvelope"];
                };
            };
        };
    };
    contests_submission_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MySubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MySubmissionRequest"];
                "multipart/form-data": components["schemas"]["MySubmissionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubmissionEnvelope"];
                };
            };
        };
    };
    contests_submission_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MySubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MySubmissionRequest"];
                "multipart/form-data": components["schemas"]["MySubmissionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubmissionEnvelope"];
                };
            };
        };
    };
    contests_featured_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedContest"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_notify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_notify_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_submissions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProfileSubmissionList"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
        };
    };
}
