# Generated by Django 5.2.7 on 2026-08-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'в очереди'), ('done', 'проверено'), ('failed', 'не удалось')], default='pending', max_length=10, verbose_name='статус')),
                ('findings', models.JSONField(blank=True, default=list, verbose_name='находки')),
                ('repo_meta', models.JSONField(blank=True, default=dict, verbose_name='о репозитории')),
                ('live_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ответ демо')),
                ('files_scanned', models.PositiveIntegerField(default=0, verbose_name='файлов проверено')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='submissions.submission', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'проверка заявки',
                'verbose_name_plural': 'проверки заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
