# Generated by Django 5.2.7 on 2026-08-31 12:14

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_contest_entry_fee_alter_contest_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('currency', models.CharField(max_length=3, verbose_name='валюта')),
                ('status', models.CharField(choices=[('awaiting_receipt', 'ждём чек'), ('pending', 'на проверке'), ('accepted', 'принят'), ('rejected', 'отклонён')], default='awaiting_receipt', max_length=20, verbose_name='статус')),
                ('receipt', models.FileField(blank=True, upload_to=apps.payments.models.receipt_path, verbose_name='чек')),
                ('telegram_file_id', models.CharField(blank=True, max_length=200, verbose_name='файл в Telegram')),
                ('expects_receipt_in_bot', models.BooleanField(default=False, verbose_name='ждём чек в боте')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='чек получен')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='проверен')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contests.contest', verbose_name='контест')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'взнос за участие',
                'verbose_name_plural': 'взносы за участие',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_en_status_57e87d_idx')],
                'constraints': [models.UniqueConstraint(fields=('contest', 'user'), name='unique_payment_per_entry')],
            },
        ),
    ]
