# Generated by Django 5.2.7 on 2026-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypayment',
            name='receipt_kind',
            field=models.CharField(blank=True, max_length=10, verbose_name='тип файла'),
        ),
    ]
