# Generated by Django 5.2.7 on 2026-09-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_entrypayment_receipt_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('requisites', models.TextField(blank=True, verbose_name='реквизиты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлены')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто изменил')),
            ],
            options={
                'verbose_name': 'реквизиты для оплаты',
                'verbose_name_plural': 'реквизиты для оплаты',
            },
        ),
    ]
