# Generated by Django 5.2.7 on 2026-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypayment',
            name='admin_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='чат администратора'),
        ),
        migrations.AddField(
            model_name='entrypayment',
            name='admin_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='сообщение с чеком'),
        ),
    ]
