# Generated by Django 5.2.7 on 2026-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_entrypayment_admin_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypayment',
            name='rejection_prompt_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='запрос причины отказа'),
        ),
    ]
