# Generated by Django 5.2.7 on 2026-08-30 15:53

import apps.contests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notify_subscription', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подписка на уведомления',
                'verbose_name_plural': 'подписки на уведомления',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='номер')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='адрес')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('requirements', models.JSONField(blank=True, default=list, validators=[apps.contests.models.validate_requirements], verbose_name='требования')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='призовой фонд')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='валюта')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='начало')),
                ('deadline', models.DateTimeField(verbose_name='дедлайн')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован'), ('archived', 'в архиве')], default='draft', max_length=16, verbose_name='статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'контест',
                'verbose_name_plural': 'контесты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'deadline'], name='contests_co_status_2b2fd3_idx')],
            },
        ),
    ]
