# Generated by Django 5.2.7 on 2026-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ноль — участие бесплатное.', max_digits=12, verbose_name='взнос за участие'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='currency',
            field=models.CharField(choices=[('USD', 'доллар США'), ('TJS', 'сомони'), ('RUB', 'рубль')], default='USD', max_length=3, verbose_name='валюта'),
        ),
    ]
