# Generated by Django 5.2.7 on 2026-09-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='событие')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='страница')),
                ('visitor', models.CharField(max_length=32, verbose_name='посетитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='analytics_e_name_6ca12c_idx'), models.Index(fields=['path', 'created_at'], name='analytics_e_path_1c5585_idx'), models.Index(fields=['visitor'], name='analytics_e_visitor_629792_idx')],
            },
        ),
    ]
